name: Download and Push Mods to Repo (with manual OptiFine)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git User
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Download Mods (excluding OptiFine)
        run: |
          mkdir -p mods && cd mods
          wget https://media.forgecdn.net/files/4614/457/iceandfire-2.1.12-1.16.5.jar -O IceAndFire.jar
          wget https://media.forgecdn.net/files/3536/25/create-mc1.16.5_v0.3.2d.jar -O Create.jar
          wget https://media.forgecdn.net/files/5846/870/jei-1.16.5-7.8.0.1013.jar -O JEI.jar
          wget https://media.forgecdn.net/files/5125/478/SpartanWeaponry-1.16.5-2.2.2.jar -O SpartanWeaponry.jar
          wget https://media.forgecdn.net/files/3765/350/FarmersDelight-1.16.5-0.6.0.jar -O FarmersDelight.jar
          wget https://media.forgecdn.net/files/3858/947/SW_Ice_and_Fire-1.16.5-0.1.3.jar -O SpartanFire.jar
          wget https://media.forgecdn.net/files/5982/776/lycanitesmobs-1.16.5-2.3.3.7.jar -O Lycanitesmobs.jar
          wget https://media.forgecdn.net/files/3740/166/FirstAid-1.16.5-1.9.8.jar -O firstaid.jar

      - name: Commit and Push Changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Modファイルを更新" || echo "コミットする変更はありません"
          git push origin HEAD:main
