name: Download and Push Mods to Repo (with manual OptiFine)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git User
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Download Mods (excluding OptiFine)
        run: |
          mkdir -p mods
          wget -O mods/IceAndFire.jar "https://media.forgecdn.net/files/4614/457/iceandfire-1.16.5-2.1.12.jar"
          wget -O mods/Create.jar "https://media.forgecdn.net/files/3536/25/create-mc1.16.5_v0.3.2d.jar"
          wget -O mods/JEI.jar "https://media.forgecdn.net/files/5846/870/jei-1.16.5-7.7.1.152.jar"
          wget -O mods/SpartanWeaponry.jar "https://media.forgecdn.net/files/5125/478/SpartanWeaponry-1.16.5-2.1.0-beta.jar"
          wget -O mods/FarmersDelight.jar "https://media.forgecdn.net/files/3765/350/FarmersDelight-1.16.5-0.5.4.jar"
          wget -O mods/SpartanFire.jar "https://media.forgecdn.net/files/3858/947/SpartanFire-2.1.5.jar"
          wget -O mods/Lycanitesmobs.jar "https://media.forgecdn.net/files/5982/776/lycanitesmobs-1.16.5-2.0.8.6.jar"
          wget -O mods/firstaid.jar "https://media.forgecdn.net/files/3740/166/FirstAid-1.9.8.jar"

      - name: Commit and Push Changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Modファイルを更新" || echo "コミットする変更はありません"
          git push origin HEAD:main
