name: Download and Push Mods to Repo (with manual OptiFine)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git User
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Download Mods (excluding OptiFine)
        run: |
          mkdir -p mods

          download_mod() {
            name="$1"
            url="$2"
            echo "Downloading $name..."
            curl -fL "$url" -o "mods/$name" || echo "Failed to download $name"
          }

          download_mod IceAndFire.jar "https://media.forgecdn.net/files/4614/457/IceAndFire-2.1.12-1.16.5.jar"
          download_mod Create.jar "https://media.forgecdn.net/files/3536/25/Create-0.3.2g.jar"
          download_mod JEI.jar "https://media.forgecdn.net/files/5846/870/jei-1.16.5-7.7.1.152.jar"
          download_mod SpartanWeaponry.jar "https://media.forgecdn.net/files/5125/478/SpartanWeaponry-2.1.0-beta.jar"
          download_mod FarmersDelight.jar "https://media.forgecdn.net/files/3765/350/FarmersDelight-0.5.4.jar"
          download_mod SpartanFire.jar "https://media.forgecdn.net/files/3858/947/SpartanFire-0.08.jar"
          download_mod Lycanitesmobs.jar "https://media.forgecdn.net/files/5982/776/LycanitesMobs-1.16.5-2.3.2.3.jar"
          download_mod firstaid.jar "https://media.forgecdn.net/files/3740/166/FirstAid-1.16.5-2.1.6.jar"

          echo "OptiFineはライセンス上、自動ダウンロードできません。手動で mods に追加してください。" > mods/README_OptiFine.txt

      - name: Commit and Push Changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git add mods
          git commit -m "Modファイルを更新（OptiFineを除く）" || echo "コミットする変更はありません"
          git pull --rebase || echo "リベースに失敗しましたが、続行します"
          git push origin HEAD:main || echo "Pushに失敗しました（競合の可能性あり）"
