name: Download and Push Mods to Repo (with manual OptiFine)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download Mods (excluding OptiFine)
        run: |
          mkdir -p mods
          curl -L -o mods/IceAndFire.jar "https://edge.forgecdn.net/files/4614/465/iceandfire-2.1.12-1.18.2.jar"
          curl -L -o mods/Create.jar "https://edge.forgecdn.net/files/4371/807/create-0.5.0i-1.18.2.jar"
          curl -L -o mods/JEI.jar "https://edge.forgecdn.net/files/3788/739/jei-1.18.2-9.7.0.195.jar"
          curl -L -o mods/SpartanWeaponry.jar "https://edge.forgecdn.net/files/5256/293/SpartanWeaponry-3.0.5-all.jar"

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add .
          git diff-index --quiet HEAD || git commit -m "Modファイルを更新"
          git push origin HEAD:main
