name: Generate Leafeau Textures

on:
  push:
    branches:
      - main

jobs:
  generate_leafeau_textures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Download Zephyr Texture
        run: |
          curl -O https://gitlab.com/Lycanite/LycanitesMobs/-/raw/2.3.3.3/src/main/resources/assets/lycanitesmobs/textures/entity/zephyr.png

      - name: Generate Leafeau Textures
        run: |
          # 通常種（黄色）
          convert zephyr.png -fill "#ffff00" -colorize 30% skycleave.png
          
          # 亜種1（灰色）
          convert zephyr.png -fill "#999999" -colorize 60% skycleave_ashen.png
          
          # 亜種2（青緑）
          convert zephyr.png -fill "#990099" -colorize 60% skycleave_violet.png

      - name: Commit and Push Changes
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_EMAIL: actions@github.com
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.SECRET_TOKEN }}@github.com/${{ github.repository }}

          git add skycleave.png skycleave_ashen.png skycleave_violet.png
          git commit -m "Generate SkyCleave textures from Zephyr base" || echo "No changes to commit"
          git pull --rebase origin main || echo "Pull failed (likely due to conflicts or clean state)"
          git push origin HEAD:main
